# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Pages/Jekyll.gitlab-ci.yml

# Template project: https://gitlab.com/pages/jekyll
# Docs: https://docs.gitlab.com/ee/pages/

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

stages:
#  - firstloop
#  - pdf
  - pages

#firstloop:
#  image: ruby:2.6
#  stage: firstloop
#  before_script:
#    - gem install bundler
#    - bundle install
#  cache:
#    paths:
#      - vendor/
#  script:
#    - bundle exec jekyll build -d public
#    - cp public/overview/frlatex.html ./content.tex
#  artifacts:
#    paths:
#      - content.tex
#  only:
#    variables:
#      - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

#pdf:
#  image: registry.gitlab.com/islandoftex/images/texlive:latest
#  stage: pdf
#  dependencies:
#    - firstloop
#  script:
#    - echo 'now create the fr.pdf ...'
#    - cp tex/fr-template.tex .
#    - pdflatex fr-template.tex
#    - mv fr-template.pdf ./fr.pdf
#    - ls -lrt ./fr.pdf
#    - rm ./content.tex
#    - rm ./fr-template.tex
#  artifacts:
#    paths:
#      - fr.pdf

pages:
  image: ruby:2.6
  stage: pages
  before_script:
    - gem install bundler
    - bundle install
  cache:
    paths:
      - vendor/
#  dependencies:
#    - pdf
  script:
    - bundle exec jekyll build -d public
  artifacts:
    paths:
      - public
  only:
    variables:
      - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
